version: '3.8'

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - "5001:5000"
    volumes:
      - "./artifacts:/data/artifacts"
    depends_on:
      - mlflow_db
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
      --artifacts-destination /data/artifacts
      --backend-store-uri postgresql://mlflow_user:mlflow_password@mlflow_db:5432/mlflow
      --gunicorn-opts "--timeout 180 --log-level debug --access-logfile -"

  mlflow_db:
    image: postgres:latest
    container_name: mlflow_db
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_password
    ports:
      - "5432:5432"
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data

volumes:
  mlflow_db_data:
